//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mercado.NFeRecepcaoEvento {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/RecepcaoEvento", ConfigurationName="NFeRecepcaoEvento.RecepcaoEventoSoap")]
    public interface RecepcaoEventoSoap {
        
        // CODEGEN: Gerando contrato de mensagem porque a operação nfeRecepcaoEvento não é RPC nem documento codificado.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.portalfiscal.inf.br/nfe/wsdl/RecepcaoEvento/nfeRecepcaoEvento", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Mercado.NFeRecepcaoEvento.nfeRecepcaoEventoResponse nfeRecepcaoEvento(Mercado.NFeRecepcaoEvento.nfeRecepcaoEventoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.portalfiscal.inf.br/nfe/wsdl/RecepcaoEvento/nfeRecepcaoEvento", ReplyAction="*")]
        System.Threading.Tasks.Task<Mercado.NFeRecepcaoEvento.nfeRecepcaoEventoResponse> nfeRecepcaoEventoAsync(Mercado.NFeRecepcaoEvento.nfeRecepcaoEventoRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/RecepcaoEvento")]
    public partial class nfeCabecMsg : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string versaoDadosField;
        
        private string cUFField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string versaoDados {
            get {
                return this.versaoDadosField;
            }
            set {
                this.versaoDadosField = value;
                this.RaisePropertyChanged("versaoDados");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string cUF {
            get {
                return this.cUFField;
            }
            set {
                this.cUFField = value;
                this.RaisePropertyChanged("cUF");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class nfeRecepcaoEventoRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/RecepcaoEvento")]
        public Mercado.NFeRecepcaoEvento.nfeCabecMsg nfeCabecMsg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/RecepcaoEvento", Order=0)]
        public System.Xml.XmlNode nfeDadosMsg;
        
        public nfeRecepcaoEventoRequest() {
        }
        
        public nfeRecepcaoEventoRequest(Mercado.NFeRecepcaoEvento.nfeCabecMsg nfeCabecMsg, System.Xml.XmlNode nfeDadosMsg) {
            this.nfeCabecMsg = nfeCabecMsg;
            this.nfeDadosMsg = nfeDadosMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class nfeRecepcaoEventoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/RecepcaoEvento", Order=0)]
        public System.Xml.XmlNode nfeRecepcaoEventoResult;
        
        public nfeRecepcaoEventoResponse() {
        }
        
        public nfeRecepcaoEventoResponse(System.Xml.XmlNode nfeRecepcaoEventoResult) {
            this.nfeRecepcaoEventoResult = nfeRecepcaoEventoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RecepcaoEventoSoapChannel : Mercado.NFeRecepcaoEvento.RecepcaoEventoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RecepcaoEventoSoapClient : System.ServiceModel.ClientBase<Mercado.NFeRecepcaoEvento.RecepcaoEventoSoap>, Mercado.NFeRecepcaoEvento.RecepcaoEventoSoap {
        
        public RecepcaoEventoSoapClient() {
        }
        
        public RecepcaoEventoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RecepcaoEventoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RecepcaoEventoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RecepcaoEventoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Mercado.NFeRecepcaoEvento.nfeRecepcaoEventoResponse Mercado.NFeRecepcaoEvento.RecepcaoEventoSoap.nfeRecepcaoEvento(Mercado.NFeRecepcaoEvento.nfeRecepcaoEventoRequest request) {
            return base.Channel.nfeRecepcaoEvento(request);
        }
        
        public System.Xml.XmlNode nfeRecepcaoEvento(Mercado.NFeRecepcaoEvento.nfeCabecMsg nfeCabecMsg, System.Xml.XmlNode nfeDadosMsg) {
            Mercado.NFeRecepcaoEvento.nfeRecepcaoEventoRequest inValue = new Mercado.NFeRecepcaoEvento.nfeRecepcaoEventoRequest();
            inValue.nfeCabecMsg = nfeCabecMsg;
            inValue.nfeDadosMsg = nfeDadosMsg;
            Mercado.NFeRecepcaoEvento.nfeRecepcaoEventoResponse retVal = ((Mercado.NFeRecepcaoEvento.RecepcaoEventoSoap)(this)).nfeRecepcaoEvento(inValue);
            return retVal.nfeRecepcaoEventoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Mercado.NFeRecepcaoEvento.nfeRecepcaoEventoResponse> Mercado.NFeRecepcaoEvento.RecepcaoEventoSoap.nfeRecepcaoEventoAsync(Mercado.NFeRecepcaoEvento.nfeRecepcaoEventoRequest request) {
            return base.Channel.nfeRecepcaoEventoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Mercado.NFeRecepcaoEvento.nfeRecepcaoEventoResponse> nfeRecepcaoEventoAsync(Mercado.NFeRecepcaoEvento.nfeCabecMsg nfeCabecMsg, System.Xml.XmlNode nfeDadosMsg) {
            Mercado.NFeRecepcaoEvento.nfeRecepcaoEventoRequest inValue = new Mercado.NFeRecepcaoEvento.nfeRecepcaoEventoRequest();
            inValue.nfeCabecMsg = nfeCabecMsg;
            inValue.nfeDadosMsg = nfeDadosMsg;
            return ((Mercado.NFeRecepcaoEvento.RecepcaoEventoSoap)(this)).nfeRecepcaoEventoAsync(inValue);
        }
    }
}
